### PR TITLE
restore fov after !matrix

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Hi
I think `timescale` sets default fov
In this proposition, there is a `wait` before restoring because when testing, my fov wasn't restored when not waiting before `setClientCvar`.

**Comment by cato-a** [comment]
Hi, can you try with `wait 0` or `wait 0.05` and change if they work?

**Comment by ghost** [comment]
Didn't work with `wait 0` but does work with `wait 0.05`
the pull request is updated

It looks something invisible appeared Line 2617 on the new commit
I think it is because I was thinking about removing this empty line but re added it using Enter key
Do I need to modify the way my Visual Studio Code does new lines/tabs for when proposing code to MiscMod?
(my VSCode uses default settings btw)

**Comment by cato-a** [comment]
Looks fine to me. You could've omitted the bracing on the for loop tho. :)

Edit: Now that I look closer at it, seems like you added a tab (4 spaces) on that one line.

**Comment by ghost** [comment]
I thought it can be done only with `if`, thank you for telling me :) :$

**Pull request merged**
