### PR TITLE
Prevent fov issue after map change

### PR DESCRIPTION
**Pull request by ghost**
When map changes and a player spawns more than 1 second after round starts, his fov will not be set. The !fov command will refuse setting his previous fov value.

### CODE REVIEW

**Comment by raphael12345678** [comment]
hi :)

**Comment by ghost** [comment]
Hi :)
I was just thinking , maybe it would be more convenient to load fov in "spawnplayer" instead of "startround"?

That would prevent the map change issue, then no need to do it in "spawnspectator"

But doing it in "spawnspectator" have the advantage of no wait time required but especially that spectators can spectate using their desired fov.

Btw why is there a wait/wait 1 required to do operations on players after spawning?

**Comment by cato-a** [comment]
hi, I think maybe we should think about writing some new code for this feature and make it proper, rather than a workaround.

Perhaps the `_loadFOV()` should be removed completely. The `wait 1;` is there to let clients connect before it's run, not very good:
https://github.com/cato-a/CoDaM_MiscMod/blob/72317515c78b10a8090f47d7a574ec7734204c9c/___CoDaM_MiscMod/codam/_mm_commands.gsc#L135

The FOV should be set here anyways, if this code doesn't work then the code probably execute too soon:
https://github.com/cato-a/CoDaM_MiscMod/blob/72317515c78b10a8090f47d7a574ec7734204c9c/___CoDaM_MiscMod/codam/miscmod.gsc#L100

**Comment by raphael12345678** [comment]
test
https://github.com/cato-a/CoDaM_MiscMod/blob/72317515c78b10a8090f47d7a574ec7734204c9c/___CoDaM_MiscMod/codam/_mm_commands.gsc#L1715
test

**Comment by ghost** [comment]
hello sorry i cancel my request

**Pull request closed without merging**
