### PR TITLE
fix spawn facing

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
I thought that the incorrect spawn facings was default to 1.1 patch.
But when "Start New Server", the spawns facings are proper.
I think the source of this issue is codam's `spawner.gsc`, line 190.

(for example, when russian on `mp_harbor`, you spawn facing to the wall)

I guess Hammer wanted to make players to look higher (-13) when spawning,
but he used `player.angles`, it returns an incorrect value for the [1] index, contrary to `getPlayerAngles()`, which I think wasn't available yet when he wrote this line.

**Comment by raphael12333** [comment]
(for example, when russian on `mp_harbor`, you spawn facing to the wall)

**Comment by cato-a** [comment]
The game has been this way since well CoDaM came around, I don't think we should remove it just like that.

I suggest the following:

```gsc
if(!codam\utils::getVar("scr", "mm_legacy_spawnangles", "bool", 1|2, false))
    self setPlayerAngles((-13, self.angles[1], 0));
```

**Comment by raphael12333** [comment]
i cancel my request

**Review by cato-a — CHANGES_REQUESTED** [review]
Let's change it to the following:

```gsc
if(!codam\utils::getVar("scr", "mm_original_spawnangles", "bool", 1|2, false))
    self setPlayerAngles((-13, self.angles[1], 0));
```

We can always decide to change it again in the future.

**Comment by cato-a** [comment]
We settled on reverting to whatever stock does.

```plaintext
￼<22:36:10> "Cheese": my opinion is to default to whatever stock does
```

**Pull request merged**
